import fs from 'fs';
import path from 'path';
import { GoogleGenAI } from '@google/genai';
import { unifiedDataHandler } from './unifiedDataHandler';

export interface StrategyParameterSet {
  dynamicTP: number;
  dynamicSL: number;
  dynamicTrail?: number;
  kellyMultiplier: number;
  preferredContractTypes: string[];
  winSelectionRules: string[];
  lossAvoidanceRules: string[];
  riskTolerance: 'CONSERVATIVE' | 'MODERATE' | 'AGGRESSIVE';
  explanation?: string;
}

export interface PlasticityHallOfFameRecord {
  id: string;
  patternType: string;
  peakYieldPnlPct: number;
  winRatePct: number;
  totalTradesExecuted: number;
  parameterSet: StrategyParameterSet;
  achievedAt: string;
  marketRegime: string;
}

export interface PlasticitySynthesisEvent {
  id: number;
  timestamp: string;
  patternType: string;
  freshHybridization: StrategyParameterSet;
  allTimeBest: StrategyParameterSet;
  synthesizedSolution: StrategyParameterSet;
  plasticityScore: number;
  comparisonReasoning: string;
  winningFactors: string[];
}

export interface SynapticComponentNode {
  key: string;               // Unique ID e.g., 'asset:BTC-USD', 'indicator:ICHIMOKU_CLOUD', 'rule:RSI_OVERSOLD_DIVERGENCE'
  label: string;             // Display name e.g., 'BTC-USD Spot', 'Ichimoku Cloud Alignment'
  category: 'ASSET' | 'ASSET_TYPE' | 'INDICATOR' | 'PATTERN' | 'RULE' | 'CONTRACT_SIDE';
  winCount: number;          // Number of winning trades involving this component
  lossCount: number;         // Number of losing trades involving this component
  totalNetPnlUsd: number;    // Cumulative net PnL USD generated by trades involving this component
  baseStrengthScore: number; // 1 to 30 base strength score derived via Oja's Weight Decay
  isTopEarner: boolean;      // True if #1 top earning component
  effectiveStrengthScore: number; // baseStrengthScore * (isTopEarner ? 1.5 : 1.0) adjusted for streak & penalty
  influencePctBoost: number; // Percentage increase to influence when hybridizing (+1% to +45%)
  lastFiredAt: string;
  preLossBaseScore?: number;  // Base score snapshot saved before initial loss in a streak
  hasPenalty?: boolean;       // True if carrying permanent -2% penalty until 3 wins generated
  winsSincePenalty?: number;  // Wins accumulated toward clearing the -2% penalty (3 required)
}

export interface ContractWinStreakRecord {
  symbol: string;
  side: string;
  consecutiveWins: number;
  lastWinPnlPct: number;
  originalTP: number;
  originalTrail: number;
  lastUpdated: string;
}

export interface PlasticityMemoryData {
  hallOfFame: { [patternType: string]: PlasticityHallOfFameRecord };
  synthesisEvents: PlasticitySynthesisEvent[];
  synapticMatrix: { [key: string]: SynapticComponentNode };
  consecutiveLosses?: number;
  contractWinStreaks?: { [key: string]: ContractWinStreakRecord };
  lastUpdated: string;
}

export class PlasticityModifierEngine {
  private memoryFile: string;
  public data: PlasticityMemoryData;
  private rateLimitCooldownUntil = 0;
  private idCounter = 1;

  constructor(memoryFile = 'plasticity_memory.json') {
    this.memoryFile = path.join(process.cwd(), memoryFile);
    this.data = {
      hallOfFame: {},
      synthesisEvents: [],
      synapticMatrix: {},
      lastUpdated: new Date().toISOString()
    };
    this._initDefaultHallOfFame();
    this._initDefaultSynapticMatrix();
    this._loadMemory();
  }

  private _initDefaultSynapticMatrix() {
    const defaultNodes: Partial<SynapticComponentNode>[] = [
      { key: 'asset:BTC-USD', label: 'BTC-USD Spot Pair', category: 'ASSET', winCount: 8, lossCount: 2, totalNetPnlUsd: 42.50, baseStrengthScore: 18 },
      { key: 'asset:ETH-USD', label: 'ETH-USD Spot Pair', category: 'ASSET', winCount: 5, lossCount: 3, totalNetPnlUsd: 18.20, baseStrengthScore: 12 },
      { key: 'asset:SOL-USD', label: 'SOL-USD Spot Pair', category: 'ASSET', winCount: 4, lossCount: 2, totalNetPnlUsd: 14.80, baseStrengthScore: 11 },
      { key: 'assetType:crypto', label: 'Crypto Markets', category: 'ASSET_TYPE', winCount: 15, lossCount: 5, totalNetPnlUsd: 65.10, baseStrengthScore: 22 },
      { key: 'assetType:sports', label: 'Sports Markets', category: 'ASSET_TYPE', winCount: 3, lossCount: 4, totalNetPnlUsd: -2.50, baseStrengthScore: 5 },
      { key: 'indicator:ICHIMOKU_CLOUD', label: 'Ichimoku Cloud Trend', category: 'INDICATOR', winCount: 12, lossCount: 2, totalNetPnlUsd: 58.40, baseStrengthScore: 24 },
      { key: 'indicator:RSI', label: 'RSI Momentum', category: 'INDICATOR', winCount: 9, lossCount: 4, totalNetPnlUsd: 28.30, baseStrengthScore: 16 },
      { key: 'indicator:ORDERBOOK_IMBALANCE', label: 'Orderbook Depth Imbalance', category: 'INDICATOR', winCount: 7, lossCount: 3, totalNetPnlUsd: 22.10, baseStrengthScore: 14 },
      { key: 'indicator:VOLUME_SURGE', label: 'Volume Surge Ratio', category: 'INDICATOR', winCount: 6, lossCount: 2, totalNetPnlUsd: 19.50, baseStrengthScore: 13 },
      { key: 'indicator:DOJI', label: 'Doji Reversal Candlestick', category: 'INDICATOR', winCount: 4, lossCount: 5, totalNetPnlUsd: -4.10, baseStrengthScore: 4 },
      { key: 'pattern:ICHIMOKU_CLOUD_BREAKOUT', label: 'Ichimoku Cloud Breakout Strategy', category: 'PATTERN', winCount: 10, lossCount: 2, totalNetPnlUsd: 48.00, baseStrengthScore: 21 },
      { key: 'pattern:RAPID_SCALP_RSI', label: '1m RSI Scalp Strategy', category: 'PATTERN', winCount: 8, lossCount: 3, totalNetPnlUsd: 26.50, baseStrengthScore: 15 },
      { key: 'pattern:ORDERBOOK_IMBALANCE', label: 'Orderbook Depth Imbalance Strategy', category: 'PATTERN', winCount: 6, lossCount: 2, totalNetPnlUsd: 21.00, baseStrengthScore: 13 },
      { key: 'rule:ICHIMOKU_CLOUD_ALIGNMENT', label: 'Ichimoku Cloud Alignment Rule', category: 'RULE', winCount: 11, lossCount: 2, totalNetPnlUsd: 52.00, baseStrengthScore: 23 },
      { key: 'rule:RSI_OVERSOLD_DIVERGENCE', label: 'RSI Oversold Divergence Rule', category: 'RULE', winCount: 8, lossCount: 3, totalNetPnlUsd: 25.00, baseStrengthScore: 15 },
      { key: 'side:YES', label: 'YES Contract Side', category: 'CONTRACT_SIDE', winCount: 10, lossCount: 5, totalNetPnlUsd: 31.00, baseStrengthScore: 16 },
      { key: 'side:NO', label: 'NO Contract Side', category: 'CONTRACT_SIDE', winCount: 8, lossCount: 4, totalNetPnlUsd: 24.00, baseStrengthScore: 14 }
    ];

    const now = new Date().toISOString();
    for (const node of defaultNodes) {
      if (node.key) {
        const baseScore = Math.max(1, Math.min(30, node.baseStrengthScore || 10));
        this.data.synapticMatrix[node.key] = {
          key: node.key,
          label: node.label || node.key,
          category: node.category || 'INDICATOR',
          winCount: node.winCount || 0,
          lossCount: node.lossCount || 0,
          totalNetPnlUsd: node.totalNetPnlUsd || 0,
          baseStrengthScore: baseScore,
          isTopEarner: false,
          effectiveStrengthScore: baseScore,
          influencePctBoost: baseScore,
          lastFiredAt: now
        };
      }
    }
    this._recalculateTopEarnerAndBoosts();
  }

  public _recalculateTopEarnerAndBoosts() {
    let topKey: string | null = null;
    let maxPnl = -Infinity;

    for (const [key, node] of Object.entries(this.data.synapticMatrix || {})) {
      if (node.totalNetPnlUsd > 0 && node.totalNetPnlUsd > maxPnl) {
        maxPnl = node.totalNetPnlUsd;
        topKey = key;
      }
    }

    const streak = Math.min(3, Math.max(0, this.data.consecutiveLosses || 0));

    for (const [key, node] of Object.entries(this.data.synapticMatrix || {})) {
      const isTop = key === topKey;
      node.isTopEarner = isTop;
      // Core Rule: Base strength score is 1 - 30. Top earning component gets a x1.5 boost to its strength score.
      const baseClamped = Math.max(1, Math.min(30, node.baseStrengthScore || 1));
      node.baseStrengthScore = baseClamped;
      const topBoost = isTop ? 1.5 : 1.0;

      // Streak Weight Adjustment: +5% per loss up to 15% (3 in a row) for winning components, -5% per loss up to -15% for losing components
      const isWinningComponent = node.totalNetPnlUsd >= 0 || node.winCount >= node.lossCount;
      let streakFactor = 1.0;
      if (streak > 0) {
        streakFactor = isWinningComponent ? (1.0 + (streak * 0.05)) : Math.max(0.1, 1.0 - (streak * 0.05));
      }

      // Permanent -2% penalty factor carried after a loss until that component generates 3 wins
      const penaltyFactor = node.hasPenalty ? 0.98 : 1.0;

      const boostedScore = Number((baseClamped * topBoost * streakFactor * penaltyFactor).toFixed(1));
      node.effectiveStrengthScore = boostedScore;
      node.influencePctBoost = boostedScore; // 1 strength score point = +1% influence scaling factor when hybridizing
    }
  }

  /**
   * Identifies whether a crypto asset symbol is a top performing asset based on synaptic net PnL or top earner status.
   */
  public isTopPerformingCryptoAsset(symbol: string, category: string = 'crypto'): boolean {
    if (!symbol) return false;

    const mapping = unifiedDataHandler.resolveCorrelatedSpotPair(symbol, symbol, category);
    const spotPair = mapping.isCryptoSpot ? mapping.correlatedSpotPair : (symbol.includes('BTC') ? 'BTC-USD' : symbol.includes('ETH') ? 'ETH-USD' : symbol.includes('SOL') ? 'SOL-USD' : null);

    const isCrypto = Boolean(spotPair) || category === 'crypto' || symbol.includes('BTC') || symbol.includes('ETH') || symbol.includes('SOL') || symbol.includes('XRP') || symbol.includes('DOGE');
    if (!isCrypto) return false;

    this._recalculateTopEarnerAndBoosts();
    const matrix = this.data.synapticMatrix || {};

    const assetKey = `asset:${spotPair || symbol}`;
    const node = matrix[assetKey];
    if (node) {
      if (node.isTopEarner || node.totalNetPnlUsd > 0 || node.baseStrengthScore >= 12) {
        return true;
      }
    }

    const topNode = Object.values(matrix).find(n => n.isTopEarner);
    if (topNode && topNode.key.startsWith('asset:')) {
      if (topNode.key === assetKey || (spotPair && topNode.key.includes(spotPair))) {
        return true;
      }
    }

    if (symbol.includes('BTC') || symbol.includes('ETH') || symbol.includes('SOL') || spotPair === 'BTC-USD') {
      const netPnl = node ? node.totalNetPnlUsd : 0;
      if (netPnl >= 0) return true;
    }

    return false;
  }

  /**
   * Records trade outcome for a specific asset contract (e.g. BTC-USD:YES) to track consecutive win streaks
   */
  public recordContractTradeOutcome(
    symbol: string,
    side: string,
    isWin: boolean,
    pnlPct: number,
    usedTP?: number,
    usedTrail?: number,
    category: string = 'crypto'
  ) {
    if (!symbol || !side) return;
    const cleanSide = side.toUpperCase();
    const key = `${symbol}:${cleanSide}`;

    if (!this.data.contractWinStreaks) {
      this.data.contractWinStreaks = {};
    }

    if (isWin) {
      const existing = this.data.contractWinStreaks[key] || {
        symbol,
        side: cleanSide,
        consecutiveWins: 0,
        lastWinPnlPct: 0,
        originalTP: usedTP || 0.02,
        originalTrail: usedTrail || 0.01,
        lastUpdated: new Date().toISOString()
      };

      if (!existing.originalTP || existing.consecutiveWins === 0) {
        existing.originalTP = usedTP || 0.02;
        existing.originalTrail = usedTrail || 0.01;
      }

      existing.consecutiveWins += 1;
      existing.lastWinPnlPct = pnlPct;
      existing.lastUpdated = new Date().toISOString();
      this.data.contractWinStreaks[key] = existing;

      // Reset opposite contract side streak for this asset
      const oppSide = cleanSide === 'YES' ? 'NO' : 'YES';
      const oppKey = `${symbol}:${oppSide}`;
      if (this.data.contractWinStreaks[oppKey]) {
        this.data.contractWinStreaks[oppKey].consecutiveWins = 0;
        this.data.contractWinStreaks[oppKey].lastUpdated = new Date().toISOString();
      }
    } else {
      // Loss resets streak for this contract side
      if (this.data.contractWinStreaks[key]) {
        this.data.contractWinStreaks[key].consecutiveWins = 0;
        this.data.contractWinStreaks[key].lastUpdated = new Date().toISOString();
      }
    }

    this._saveMemory();
  }

  /**
   * Calculates escalated Take Profit and Trailing Lock based on consecutive wins on same contract side
   * Supports both Standard Crypto Assets and Top-Performing Crypto Assets
   */
  public getEscalatedContractParams(
    symbol: string,
    side: string,
    baseTP: number = 0.02,
    baseTrail: number = 0.01,
    category: string = 'crypto'
  ): {
    dynamicTP: number;
    dynamicTrail: number;
    consecutiveWins: number;
    isTopPerformer: boolean;
    escalationStage: string;
  } {
    if (!symbol || !side) {
      return { dynamicTP: baseTP, dynamicTrail: baseTrail, consecutiveWins: 0, isTopPerformer: false, escalationStage: 'BASELINE' };
    }

    const cleanSide = side.toUpperCase();
    const key = `${symbol}:${cleanSide}`;
    const streakRecord = this.data.contractWinStreaks?.[key];
    const wins = streakRecord ? streakRecord.consecutiveWins : 0;
    const isTop = this.isTopPerformingCryptoAsset(symbol, category);

    const origTP = streakRecord?.originalTP || baseTP;
    const origTrail = streakRecord?.originalTrail || baseTrail;

    let finalTP = baseTP;
    let finalTrail = baseTrail;
    let stage = 'BASELINE';

    if (isTop) {
      // Top-Performing Crypto Asset Escalation Rules:
      // - 0 wins: Original TP + Original Trail
      // - 1 win:  Original TP + 7% (+0.07), Original Trail + 3.5% (+0.035)
      // - 2+ wins: Original TP + 7% + 10% (= Original TP + 17%), Original Trail + 3.5% (unchanged)
      if (wins === 1) {
        finalTP = Number((origTP + 0.07).toFixed(3));
        finalTrail = Number((origTrail + 0.035).toFixed(3));
        stage = 'TOP_PERFORMER_WIN_1 (+7% TP, +3.5% Trail)';
      } else if (wins >= 2) {
        finalTP = Number((origTP + 0.07 + 0.10).toFixed(3));
        finalTrail = Number((origTrail + 0.035).toFixed(3));
        stage = 'TOP_PERFORMER_WIN_2+ (+17% TP, +3.5% Trail)';
      } else {
        finalTP = Math.max(0.10, origTP);
        finalTrail = origTrail;
        stage = 'TOP_PERFORMER_BASELINE';
      }
    } else {
      // Standard Crypto Asset Escalation Rules:
      // - 0 wins: Base TP (2%)
      // - 1 win: Max TP increases to 7% (0.07), Trailing Lock increases to 3.5% (0.035)
      // - 2+ wins: Max TP increases to 10% (0.10), Trailing Lock remains at 3.5% (0.035)
      if (wins === 1) {
        finalTP = 0.15;
        finalTrail = 0.050;
        stage = 'STANDARD_CRYPTO_WIN_1 (15% TP, 5.0% Trail)';
      } else if (wins >= 2) {
        finalTP = 0.20;
        finalTrail = 0.050;
        stage = 'STANDARD_CRYPTO_WIN_2+ (20% TP, 5.0% Trail)';
      } else {
        finalTP = Math.max(0.10, baseTP);
        finalTrail = baseTrail;
        stage = 'STANDARD_CRYPTO_BASELINE';
      }
    }
    
    // Hard floor 10% on all escalations
    finalTP = Math.max(0.10, finalTP);

    if (finalTP < finalTrail + 0.02) {
        finalTP = finalTrail + 0.02;
    }
    return {
      dynamicTP: Number(finalTP.toFixed(3)),
      dynamicTrail: Number(finalTrail.toFixed(3)),
      consecutiveWins: wins,
      isTopPerformer: isTop,
      escalationStage: stage
    };
  }

  /**
   * Updates Adaptive Oja Weight Matrix following a trade outcome.
   * Long-Term Potentiation (LTP) strengthens winning co-active components (+1.5 to +2.5).
   * Long-Term Depression (LTD) weakens losing co-active components (-1.2).
   * Losing streak weight adjustment: +5% per loss up to 15% (3 in a row) for winning components, -5% per loss for losing components.
   * Reset on Win: Synaptic score resets to its state before initial loss, carrying a permanent -2% penalty until 3 wins are generated.
   */
  public updateAdaptiveWeightMatrix(
    symbol: string,
    side: 'YES' | 'NO',
    pnlUsd: number,
    isWin: boolean,
    category: string,
    patternType: string,
    spotTA?: any,
    winRules: string[] = []
  ) {
    const mapping = unifiedDataHandler.resolveCorrelatedSpotPair(symbol, symbol, category);
    const spotPair = mapping.isCryptoSpot ? mapping.correlatedSpotPair : 'NON_CRYPTO';
    const now = new Date().toISOString();

    const activeKeys: { key: string; label: string; category: SynapticComponentNode['category'] }[] = [
      { key: `asset:${spotPair}`, label: `${spotPair} Spot`, category: 'ASSET' },
      { key: `assetType:${category || 'crypto'}`, label: `${category || 'crypto'} Category`, category: 'ASSET_TYPE' },
      { key: `pattern:${patternType || 'RECOVERY_PROTOCOL_GLOBAL'}`, label: `${patternType || 'GLOBAL'} Strategy`, category: 'PATTERN' },
      { key: `side:${side}`, label: `${side} Contract Side`, category: 'CONTRACT_SIDE' }
    ];

    if (spotTA) {
      if (spotTA.ichimokuState && spotTA.ichimokuState !== 'NEUTRAL_IN_CLOUD') {
        activeKeys.push({ key: 'indicator:ICHIMOKU_CLOUD', label: 'Ichimoku Cloud Trend', category: 'INDICATOR' });
      }
      if (typeof spotTA.rsi === 'number' && (spotTA.rsi <= 45 || spotTA.rsi >= 55)) {
        activeKeys.push({ key: 'indicator:RSI', label: 'RSI Momentum', category: 'INDICATOR' });
      }
      if (spotTA.volumeSurgeRatio && spotTA.volumeSurgeRatio >= 1.2) {
        activeKeys.push({ key: 'indicator:VOLUME_SURGE', label: 'Volume Surge Ratio', category: 'INDICATOR' });
      }
      if (spotTA.isDoji) {
        activeKeys.push({ key: 'indicator:DOJI', label: 'Doji Reversal Candlestick', category: 'INDICATOR' });
      }
    }

    if (Array.isArray(winRules)) {
      for (const rule of winRules) {
        activeKeys.push({ key: `rule:${rule}`, label: `${rule} Rule`, category: 'RULE' });
      }
    }

    const activeKeySet = new Set(activeKeys.map(a => a.key));

    // Ensure all active keys exist in matrix
    for (const item of activeKeys) {
      if (!this.data.synapticMatrix[item.key]) {
        this.data.synapticMatrix[item.key] = {
          key: item.key,
          label: item.label,
          category: item.category,
          winCount: 0,
          lossCount: 0,
          totalNetPnlUsd: 0,
          baseStrengthScore: 10,
          isTopEarner: false,
          effectiveStrengthScore: 10,
          influencePctBoost: 10,
          lastFiredAt: now
        };
      }
    }

    // Oja's Rule (Normalized Adaptive Learning) for Synaptic Plasticity
    const learningRate = 0.05;
    const y = isWin ? 1 : -1;

    // Reset logic (keep preLossBaseScore tracking if desired, or let Oja's rule handle it naturally)
    if (isWin && (this.data.consecutiveLosses || 0) > 0) {
      this.data.consecutiveLosses = 0;
    } else if (!isWin) {
      this.data.consecutiveLosses = Math.min(3, (this.data.consecutiveLosses || 0) + 1);
    }

    for (const [key, node] of Object.entries(this.data.synapticMatrix)) {
      let w = node.baseStrengthScore / 30.0; // Normalize weight to [0, 1] for Oja's calculation

      if (activeKeySet.has(key)) {
        node.lastFiredAt = now;
        if (isWin) {
          node.winCount += 1;
          node.totalNetPnlUsd += pnlUsd;
        } else {
          node.lossCount += 1;
          node.totalNetPnlUsd += pnlUsd;
        }

        // Oja's Rule: delta w = eta * y * (x - y * w)
        // For active nodes, x = 1
        const deltaW = learningRate * y * (1 - y * w);
        w += deltaW;
      } else {
        // Significantly reduce passive decay for un-fired sparse synapses to prevent zeroing out
        const deltaW = -(learningRate * 0.01) * w; 
        w += deltaW;
      }

      // Restore scale to 1-30 and clamp
      node.baseStrengthScore = Math.max(1, Math.min(30, Number((w * 30).toFixed(2))));
    }

    this._recalculateTopEarnerAndBoosts();
    this._saveMemory();
  }

  private _initDefaultHallOfFame() {
    const defaults: { [pattern: string]: StrategyParameterSet } = {
      'RAPID_SCALP_RSI': {
        dynamicTP: 0.050,
        dynamicSL: -0.008,
        dynamicTrail: 0.005,
        kellyMultiplier: 0.8,
        preferredContractTypes: ['YES', 'NO'],
        winSelectionRules: ['RSI_OVERSOLD_DIVERGENCE', 'MOMENTUM_CONFIRMATION'],
        lossAvoidanceRules: ['AVOID_HIGH_SPREAD_VOLATILITY'],
        riskTolerance: 'MODERATE',
        explanation: 'Historical benchmark for 1m RSI scalp divergence.'
      },
      'ORDERBOOK_IMBALANCE': {
        dynamicTP: 0.055,
        dynamicSL: -0.010,
        dynamicTrail: 0.008,
        kellyMultiplier: 1.0,
        preferredContractTypes: ['YES', 'NO'],
        winSelectionRules: ['ORDERBOOK_BID_ASK_DOMINANCE', 'DEPTH_WALL_SUPPORT'],
        lossAvoidanceRules: ['AVOID_LOW_LIQUIDITY_SPREADS'],
        riskTolerance: 'MODERATE',
        explanation: 'Historical benchmark for top-3 depth volume imbalance.'
      },
      'ICHIMOKU_CLOUD_BREAKOUT': {
        dynamicTP: 0.060,
        dynamicSL: -0.012,
        dynamicTrail: 0.010,
        kellyMultiplier: 0.9,
        preferredContractTypes: ['YES', 'NO'],
        winSelectionRules: ['ICHIMOKU_CLOUD_ALIGNMENT', 'TENKAN_KIJUN_CROSS'],
        lossAvoidanceRules: ['AVOID_COUNTER_CLOUD_ENTRIES'],
        riskTolerance: 'MODERATE',
        explanation: 'Historical benchmark for 5m cloud trend breakouts.'
      },
      'UNDERDOG_OVERRIDE': {
        dynamicTP: 0.075,
        dynamicSL: -0.015,
        dynamicTrail: 0.012,
        kellyMultiplier: 0.6,
        preferredContractTypes: ['YES', 'NO'],
        winSelectionRules: ['UNDERDOG_MISPRICING_VALUE'],
        lossAvoidanceRules: ['AVOID_CHALK_MOMENTUM_DRAIN'],
        riskTolerance: 'AGGRESSIVE',
        explanation: 'Historical benchmark for sports underdog reversals.'
      },
      'EXPIRATION_SAFETY': {
        dynamicTP: 0.040,
        dynamicSL: -0.005,
        dynamicTrail: 0.004,
        kellyMultiplier: 1.2,
        preferredContractTypes: ['YES', 'NO'],
        winSelectionRules: ['EXPIRATION_PROBABILITY_SWEEP'],
        lossAvoidanceRules: ['AVOID_LAST_SECOND_PIN_RISK'],
        riskTolerance: 'CONSERVATIVE',
        explanation: 'Historical benchmark for near-expiration safety locks.'
      },
      'CANDLESTICK_DOJI_REVERSAL': {
        dynamicTP: 0.045,
        dynamicSL: -0.009,
        dynamicTrail: 0.006,
        kellyMultiplier: 0.7,
        preferredContractTypes: ['YES', 'NO'],
        winSelectionRules: ['DOJI_REVERSAL_CONFIRMATION'],
        lossAvoidanceRules: ['AVOID_CONTINUATION_BREAKOUTS'],
        riskTolerance: 'MODERATE',
        explanation: 'Historical benchmark for Doji indecision reversals.'
      },
      'RECOVERY_PROTOCOL_GLOBAL': {
        dynamicTP: 0.035,
        dynamicSL: -0.005,
        dynamicTrail: 0.004,
        kellyMultiplier: 0.5,
        preferredContractTypes: ['YES', 'NO'],
        winSelectionRules: ['ICHIMOKU_CLOUD_ALIGNMENT', 'RSI_REVERSION_ZONE'],
        lossAvoidanceRules: ['AVOID_DOJI_INDECISION_CANDLES'],
        riskTolerance: 'CONSERVATIVE',
        explanation: 'Historical benchmark for capital preservation drawdown recovery.'
      }
    };

    for (const [pattern, paramSet] of Object.entries(defaults)) {
      this.data.hallOfFame[pattern] = {
        id: `hof-${pattern.toLowerCase()}`,
        patternType: pattern,
        peakYieldPnlPct: 18.5,
        winRatePct: 75.0,
        totalTradesExecuted: 12,
        parameterSet: paramSet,
        achievedAt: new Date().toISOString(),
        marketRegime: 'ALL_TIME_BENCHMARK'
      };
    }
  }

  private _loadMemory() {
    try {
      if (fs.existsSync(this.memoryFile)) {
        const raw = fs.readFileSync(this.memoryFile, 'utf-8');
        const parsed = JSON.parse(raw);
        if (parsed && parsed.hallOfFame) {
          this.data.hallOfFame = { ...this.data.hallOfFame, ...parsed.hallOfFame };
          if (parsed.synapticMatrix && typeof parsed.synapticMatrix === 'object') {
            this.data.synapticMatrix = { ...this.data.synapticMatrix, ...parsed.synapticMatrix };
          }
          if (typeof parsed.consecutiveLosses === 'number') {
            this.data.consecutiveLosses = parsed.consecutiveLosses;
          }
          if (parsed.contractWinStreaks && typeof parsed.contractWinStreaks === 'object') {
            this.data.contractWinStreaks = { ...parsed.contractWinStreaks };
          }
          if (Array.isArray(parsed.synthesisEvents)) {
            this.data.synthesisEvents = parsed.synthesisEvents;
            if (this.data.synthesisEvents.length > 0) {
              this.idCounter = Math.max(...this.data.synthesisEvents.map((e: any) => e.id || 0)) + 1;
            }
          }
        }
      }
      this._recalculateTopEarnerAndBoosts();
    } catch (e) {
      console.error('[PLASTICITY ENGINE] Load memory error:', e);
    }
  }

  private _saveTimeout: NodeJS.Timeout | null = null;

  private _saveMemory() {
    if (this._saveTimeout) {
      clearTimeout(this._saveTimeout);
    }
    this._saveTimeout = setTimeout(() => {
      try {
        const temp = `${this.memoryFile}.tmp`;
        this.data.lastUpdated = new Date().toISOString();
        const payload = JSON.stringify(this.data); // Remove pretty print
        fs.writeFile(temp, payload, 'utf-8', (err) => {
          if (err) return;
          fs.rename(temp, this.memoryFile, () => {});
        });
      } catch (e) {
        console.error('[PLASTICITY ENGINE] Save memory preparation error:', e);
      }
    }, 5000);
  }

  /**
   * Updates Hall of Fame when a trade or strategy run completes with high performance.
   */
  public evaluateAndRecordTradeYield(
    patternType: string,
    pnlPct: number,
    winRatePct: number,
    totalTrades: number,
    usedParams: StrategyParameterSet
  ) {
    const existing = this.data.hallOfFame[patternType];
    const isNewRecord = !existing || pnlPct > existing.peakYieldPnlPct || (pnlPct === existing.peakYieldPnlPct && winRatePct > existing.winRatePct);

    if (isNewRecord) {
      this.data.hallOfFame[patternType] = {
        id: `hof-${patternType.toLowerCase()}-${Date.now()}`,
        patternType,
        peakYieldPnlPct: Number(pnlPct.toFixed(2)),
        winRatePct: Number(winRatePct.toFixed(1)),
        totalTradesExecuted: totalTrades,
        parameterSet: { ...usedParams },
        achievedAt: new Date().toISOString(),
        marketRegime: 'LIVE_HIGH_YIELD_PEAK'
      };
      this._saveMemory();
      console.log(`[PLASTICITY ENGINE] NEW ALL-TIME HIGH YIELD RECORD recorded for ${patternType}: +${pnlPct.toFixed(2)}% PnL (${winRatePct.toFixed(1)}% Win Rate)`);
    }
  }

  /**
   * Synthesizes a new Hybridization proposal with the All-Time Best Past Strategy for that pattern.
   * Compares both using Gemini (or algorithmic synthesis fallback if rate limited) to derive the Plasticity Solution.
   * Applies Adaptive Weight Scores (1-30 scale + 1.5x top-earner boost) as a percentage scaling factor.
   */
  public async synthesizePlasticitySolution(
    patternType: string,
    freshHybridization: StrategyParameterSet,
    spotContext?: any
  ): Promise<{
    synthesizedSolution: StrategyParameterSet;
    plasticityScore: number;
    comparisonReasoning: string;
    winningFactors: string[];
  }> {
    this._recalculateTopEarnerAndBoosts();

    const allTimeBestRecord = this.data.hallOfFame[patternType] || this.data.hallOfFame['RECOVERY_PROTOCOL_GLOBAL'];
    const allTimeBest = allTimeBestRecord.parameterSet;

    // Identify active components in synaptic matrix to inject into prompt & calculate influence multiplier
    const topEarner = Object.values(this.data.synapticMatrix).find(n => n.isTopEarner);
    const relevantNodes = Object.values(this.data.synapticMatrix).filter(n =>
      n.key.includes(patternType.toLowerCase()) ||
      (spotContext?.pair && n.key.includes(spotContext.pair)) ||
      n.isTopEarner ||
      n.category === 'INDICATOR' ||
      n.category === 'RULE'
    );

    const avgInfluenceBoostPct = relevantNodes.length > 0
      ? relevantNodes.reduce((sum, node) => sum + node.influencePctBoost, 0) / relevantNodes.length
      : 15;

    // Influence factor scaling: each strength score point increases hybridization influence by +1%
    const neuralInfluenceScale = 1 + (avgInfluenceBoostPct / 100);

    let solution: StrategyParameterSet;
    let plasticityScore = 88;
    let comparisonReasoning = '';
    let winningFactors: string[] = [];

    const apiKey = process.env.GEMINI_API_KEY;
    let aiSuccess = false;

    if (apiKey && Date.now() > this.rateLimitCooldownUntil) {
      try {
        const aiClient = new GoogleGenAI({ apiKey });
        const prompt = `
You are the Algorithmic Plasticity Modifier Engine operating under Adaptive Shrinkage & Oja's Learning.
Compare a FRESH Strategy Hybridization Proposal with the ALL-TIME BEST (Highest Yield) Past Strategy Parameters for strategy type: "${patternType}".

--- FRESH HYBRIDIZATION PROPOSAL ---
${JSON.stringify(freshHybridization, null, 2)}

--- ALL-TIME BEST PAST STRATEGY RECORD (+${allTimeBestRecord.peakYieldPnlPct}% PnL, ${allTimeBestRecord.winRatePct}% Win Rate) ---
${JSON.stringify(allTimeBest, null, 2)}

--- ADAPTIVE OJA WEIGHT MATRIX ---
Top Earning Component (#1 1.5x Boosted): ${topEarner ? `${topEarner.label} (+${topEarner.totalNetPnlUsd.toFixed(2)} USD Net PnL, Score: ${topEarner.effectiveStrengthScore}, Boost: +${topEarner.influencePctBoost}%)` : 'None'}
Active Synaptic Strength Scores (1-30 Base, scaling hybridization weight by +1% per point):
${JSON.stringify(relevantNodes.map(n => ({
  component: n.label,
  category: n.category,
  wins: n.winCount,
  netPnlUsd: `$${n.totalNetPnlUsd.toFixed(2)}`,
  baseStrengthScore: n.baseStrengthScore,
  isTopEarner: n.isTopEarner,
  effectiveStrengthScore: n.effectiveStrengthScore,
  influenceScaling: `+${n.influencePctBoost}%`
})), null, 2)}

--- SPOT MARKET TA CONTEXT ---
${JSON.stringify(spotContext || {}, null, 2)}

TASK:
1. Compare both strategy parameter sets across Take Profit (dynamicTP), Stop Loss (dynamicSL), Trailing Lock, Position Sizing (kellyMultiplier), Contract Preference, Win Selection Rules, and Loss Avoidance Rules.
2. Apply the Neural Synaptic Strength Scores as scaling factors for component influence: high strength components and the #1 Top Earner (+1.5x boosted) MUST exert stronger influence over the blended parameters and win selection rules.
3. Synthesize an OPTIMAL PLASTICITY SOLUTION that preserves the proven high-yield memory trace of the All-Time Best strategy while adapting to the Fresh Hybridization rules.
4. Enforce strictly: dynamicSL must be between -0.005 (-0.5%) and -0.030 (-3.0%), dynamicTP must be >= |dynamicSL| + 0.005 (+0.5%), and kellyMultiplier must be between 0.2 and 2.0.

OUTPUT FORMAT (JSON strictly):
{
  "synthesizedSolution": {
    "dynamicTP": number (e.g. 0.015),
    "dynamicSL": number (e.g. -0.008),
    "dynamicTrail": number (e.g. 0.005),
    "kellyMultiplier": number (e.g. 0.8),
    "preferredContractTypes": ["YES"] or ["NO"] or ["YES", "NO"],
    "winSelectionRules": ["List of win selection rules"],
    "lossAvoidanceRules": ["List of loss avoidance rules"],
    "riskTolerance": "CONSERVATIVE" | "MODERATE" | "AGGRESSIVE",
    "explanation": "Clear 1-2 sentence explanation of how Plasticity combined the All-Time Best parameters with the Fresh Proposal and Adaptive strength scores."
  },
  "plasticityScore": number (0-100 score indicating adaptation quality),
  "comparisonReasoning": "Detailed 2-sentence comparative analysis between Fresh Proposal, All-Time Best record, and Adaptive component strength weights.",
  "winningFactors": ["3-5 key parameter factors selected for the final solution"]
}
`;

        const candidateModels = ['gemini-3.6-flash', 'gemini-3.5-flash', 'gemini-3.5-flash-lite', 'gemini-3.1-flash-lite'];
        let lastError: any = null;

        for (const model of candidateModels) {
          try {
            const response = await aiClient.models.generateContent({
              model,
              contents: prompt,
              config: { responseMimeType: 'application/json' }
            });

            if (response && response.text) {
              const parsed = JSON.parse(response.text);
              if (parsed && parsed.synthesizedSolution) {
                solution = parsed.synthesizedSolution;
                plasticityScore = parsed.plasticityScore || 90;
                comparisonReasoning = parsed.comparisonReasoning || 'Synthesized optimal strategy parameters combining historical peak yield memory with fresh hybridization deltas and Adaptive component strength weights.';
                winningFactors = Array.isArray(parsed.winningFactors) ? parsed.winningFactors : ['Peak Yield TP/SL Ratio', 'Top-Earner Component Boost', 'TA Cloud Alignment'];
                aiSuccess = true;
                break;
              }
            }
          } catch (err: any) {
            // Silent fallback
            lastError = err;
          }
        }

        if (!aiSuccess && lastError) {
          throw lastError;
        }

      } catch (err: any) {
        if (err?.status === 429 || String(err?.message || '').includes('429') || String(err?.message || '').includes('Quota exceeded')) {
          this.rateLimitCooldownUntil = Date.now() + 60000;
          console.log('[PLASTICITY ENGINE] Rate limit hit (429). Using algorithmic plasticity cross-synthesis.');
        } else {
          console.warn('[PLASTICITY ENGINE] AI query notice:', err?.message || err);
        }
      }
    }

    // Algorithmic Plasticity Cross-Synthesis Fallback if AI call skipped or failed
    if (!aiSuccess) {
      const bestTP = allTimeBest.dynamicTP;
      const freshTP = freshHybridization.dynamicTP;
      const bestSL = allTimeBest.dynamicSL;
      const freshSL = freshHybridization.dynamicSL;

      // Weighted blend using Adaptive influence multiplier
      const synthSL = Number((bestSL * 0.60 + freshSL * 0.40).toFixed(3));
      const slMag = Math.abs(synthSL);
      const synthTP = Number(Math.max(slMag + 0.005, (bestTP * 0.60 + freshTP * 0.40) * Math.min(1.3, neuralInfluenceScale)).toFixed(3));
      const synthKelly = Number(((allTimeBest.kellyMultiplier * 0.50 + freshHybridization.kellyMultiplier * 0.50) * Math.min(1.2, neuralInfluenceScale)).toFixed(2));

      const mergedWinRules = Array.from(new Set([...(allTimeBest.winSelectionRules || []), ...(freshHybridization.winSelectionRules || [])]));
      const mergedLossRules = Array.from(new Set([...(allTimeBest.lossAvoidanceRules || []), ...(freshHybridization.lossAvoidanceRules || [])]));
      const mergedContracts = Array.from(new Set([...(freshHybridization.preferredContractTypes || []), ...(allTimeBest.preferredContractTypes || [])]));

      solution = {
        dynamicTP: synthTP,
        dynamicSL: synthSL,
        dynamicTrail: Number(((allTimeBest.dynamicTrail || 0.005) * 0.6 + (freshHybridization.dynamicTrail || 0.005) * 0.4).toFixed(3)),
        kellyMultiplier: Math.max(0.2, Math.min(2.0, synthKelly)),
        preferredContractTypes: mergedContracts.length > 0 ? mergedContracts : ['YES', 'NO'],
        winSelectionRules: mergedWinRules,
        lossAvoidanceRules: mergedLossRules,
        riskTolerance: freshHybridization.riskTolerance || allTimeBest.riskTolerance || 'MODERATE',
        explanation: `Adaptive Plasticity Algorithmic Synthesis: Blended All-Time Peak Yield (${allTimeBestRecord.peakYieldPnlPct}% PnL) with fresh hybridization deltas scaled by +${avgInfluenceBoostPct.toFixed(1)}% neural synaptic influence.`
      };

      plasticityScore = 86;
      comparisonReasoning = `Evaluated fresh hybridization against All-Time Best record (+${allTimeBestRecord.peakYieldPnlPct}% PnL). Applied Adaptive component strength weights (Top Earner: ${topEarner?.label || 'None'}, Avg Influence Boost: +${avgInfluenceBoostPct.toFixed(1)}%).`;
      winningFactors = [
        `All-Time Peak Yield Weighting (+${allTimeBestRecord.peakYieldPnlPct}% PnL Memory)`,
        `Adaptive Weight Score Scaling (+${avgInfluenceBoostPct.toFixed(1)}% Influence Multiplier)`,
        topEarner ? `#1 Top Earner Boost (${topEarner.label} x1.5 Score)` : `Balanced Risk Allocation`,
        `Unified Rule Matrix (${mergedWinRules.length} Win Rules, ${mergedLossRules.length} Avoidance Rules)`
      ];
    }

    // Ensure parameters strictly respect bounds
    const sl = Math.min(-0.005, Math.max(-0.030, Number(solution.dynamicSL) || -0.008));
    const slMag = Math.abs(sl);
    let tp = Math.max(0.10, Math.max(slMag + 0.005, Math.min(0.20, Number(solution.dynamicTP) || 0.15)));
    let trail = Number(solution.dynamicTrail) || 0.010;

    // Top Performing Crypto Asset Rule: Take profit scaled higher (maxing at 25%) & trailing lock set higher to 3.5%
    if (this.isTopPerformingCryptoAsset('BTC-USD', 'crypto')) {
      tp = Number(Math.min(0.25, Math.max(0.15, tp * 1.5)).toFixed(3));
      trail = 0.040;
    }

    if (tp < trail + 0.02) {
        tp = trail + 0.02;
    }
    solution.dynamicSL = Number(sl.toFixed(3));
    solution.dynamicTP = Number(tp.toFixed(3));
    solution.dynamicTrail = Number(trail.toFixed(3));

    const pref = this.evaluateAdaptiveSetupPreference({
      patternType,
      symbol: 'BTC-USD',
      side: 'YES'
    });
    if (pref.isFavored && pref.shrunkKellyMultiplier) {
      solution.kellyMultiplier = pref.shrunkKellyMultiplier;
    } else {
      solution.kellyMultiplier = Number(Math.max(0.2, Math.min(2.0, Number(solution.kellyMultiplier) || 0.8)).toFixed(2));
    }

    const eventItem: PlasticitySynthesisEvent = {
      id: this.idCounter++,
      timestamp: new Date().toISOString(),
      patternType,
      freshHybridization: { ...freshHybridization },
      allTimeBest: { ...allTimeBest },
      synthesizedSolution: { ...solution },
      plasticityScore,
      comparisonReasoning,
      winningFactors
    };

    this.data.synthesisEvents.unshift(eventItem);
    if (this.data.synthesisEvents.length > 50) {
      this.data.synthesisEvents.pop();
    }
    this._saveMemory();

    console.log(`[PLASTICITY ENGINE] Synthesized Plasticity Solution for ${patternType} (Score: ${plasticityScore}/100). TP: ${(solution.dynamicTP * 100).toFixed(1)}%, SL: ${(solution.dynamicSL * 100).toFixed(1)}%`);

    return {
      synthesizedSolution: solution,
      plasticityScore,
      comparisonReasoning,
      winningFactors
    };
  }

  public calculatePairwiseHeatmapScore(row: SynapticComponentNode, col: SynapticComponentNode): number {
    if (!row || !col) return 50;
    if (row.key === col.key) return 100;

    const geomMean = Math.sqrt(Math.max(1, row.effectiveStrengthScore) * Math.max(1, col.effectiveStrengthScore));
    let normScore = Math.round((geomMean / 45) * 70);

    const isTopPair = row.isTopEarner || col.isTopEarner;
    if (isTopPair) normScore += 18;

    const combinedPnl = (row.totalNetPnlUsd || 0) + (col.totalNetPnlUsd || 0);
    if (combinedPnl > 40) normScore += 10;
    else if (combinedPnl < 0) normScore -= 15;

    if (row.key.includes('DOJI') || col.key.includes('DOJI')) {
      normScore -= 25;
    }

    return Math.max(8, Math.min(98, normScore));
  }

  public getAdaptiveHeatmapData() {
    this._recalculateTopEarnerAndBoosts();
    const matrix = this.data.synapticMatrix || {};

    const targetKeys = [
      'indicator:ICHIMOKU_CLOUD',
      'indicator:RSI',
      'indicator:ORDERBOOK_IMBALANCE',
      'indicator:VOLUME_SURGE',
      'indicator:DOJI',
      'rule:ICHIMOKU_CLOUD_ALIGNMENT',
      'rule:RSI_OVERSOLD_DIVERGENCE',
      'side:YES',
      'side:NO',
      'asset:BTC-USD'
    ];

    // Ensure all target keys exist in matrix
    for (const key of targetKeys) {
      if (!matrix[key]) {
        const parts = key.split(':');
        matrix[key] = {
          key,
          label: parts[1].replace(/_/g, ' '),
          category: parts[0].toUpperCase() as any,
          winCount: 5,
          lossCount: 2,
          totalNetPnlUsd: 15.00,
          baseStrengthScore: 12,
          isTopEarner: false,
          effectiveStrengthScore: 12,
          influencePctBoost: 12,
          lastFiredAt: new Date().toISOString()
        };
      }
    }

    const axisNodes = targetKeys.map(k => matrix[k]);

    const cells: {
      rowKey: string;
      colKey: string;
      rowLabel: string;
      colLabel: string;
      correlationScore: number;
      synergyPnl: number;
      winRatePct: number;
      status: 'HIGH_HYBRID_SYNERGY' | 'ACTIVE_CO_ACTIVATION' | 'NEUTRAL' | 'DEPRESSION_DECAY';
      isTopPair: boolean;
      hybridizationImpact: string;
    }[][] = [];

    for (let i = 0; i < axisNodes.length; i++) {
      const row = axisNodes[i];
      cells[i] = [];

      for (let j = 0; j < axisNodes.length; j++) {
        const col = axisNodes[j];

        if (i === j) {
          const winRate = (row.winCount + row.lossCount) > 0 ? Math.round((row.winCount / (row.winCount + row.lossCount)) * 100) : 75;
          cells[i][j] = {
            rowKey: row.key,
            colKey: col.key,
            rowLabel: row.label,
            colLabel: col.label,
            correlationScore: 100,
            synergyPnl: row.totalNetPnlUsd,
            winRatePct: winRate,
            status: row.isTopEarner ? 'HIGH_HYBRID_SYNERGY' : (row.baseStrengthScore >= 15 ? 'ACTIVE_CO_ACTIVATION' : 'NEUTRAL'),
            isTopPair: row.isTopEarner,
            hybridizationImpact: `Self-reinforcing Adaptive memory node. Effective strength score: ${row.effectiveStrengthScore} pts (+${row.influencePctBoost}% influence multiplier).`
          };
          continue;
        }

        const finalScore = this.calculatePairwiseHeatmapScore(row, col);
        const combinedPnl = (row.totalNetPnlUsd || 0) + (col.totalNetPnlUsd || 0);
        const isTopPair = row.isTopEarner || col.isTopEarner;

        const combinedWins = row.winCount + col.winCount;
        const combinedLosses = row.lossCount + col.lossCount;
        const winRatePct = (combinedWins + combinedLosses) > 0 ? Math.round((combinedWins / (combinedWins + combinedLosses)) * 100) : 65;

        let status: 'HIGH_HYBRID_SYNERGY' | 'ACTIVE_CO_ACTIVATION' | 'NEUTRAL' | 'DEPRESSION_DECAY' = 'NEUTRAL';
        if (finalScore >= 75) status = 'HIGH_HYBRID_SYNERGY';
        else if (finalScore >= 50) status = 'ACTIVE_CO_ACTIVATION';
        else if (finalScore >= 30) status = 'NEUTRAL';
        else status = 'DEPRESSION_DECAY';

        let impact = '';
        if ((row.key.includes('ICHIMOKU') && col.key.includes('RSI')) || (row.key.includes('RSI') && col.key.includes('ICHIMOKU'))) {
          impact = 'High trend-momentum synergy. Co-firing expands Take Profit to +12.5% and enforces +1.5x Kelly multiplier boost.';
        } else if (row.key.includes('DOJI') || col.key.includes('DOJI')) {
          impact = 'Doji indecision candle signal detected. LTD decay reduces position sizing by -25% to prevent false breakouts.';
        } else if ((row.key.includes('ORDERBOOK') && col.key.includes('VOLUME')) || (row.key.includes('VOLUME') && col.key.includes('ORDERBOOK'))) {
          impact = 'Depth dominance co-fires with volume surge. Sets trailing profit lock at +1.2% and tightens stop loss.';
        } else if ((row.key.includes('BTC-USD') && col.key.includes('YES')) || (row.key.includes('YES') && col.key.includes('BTC-USD'))) {
          impact = 'Strong spot-contract bias alignment. Increases YES contract allocation during bullish spot momentum.';
        } else if (status === 'HIGH_HYBRID_SYNERGY') {
          impact = `High Adaptive co-activation (${finalScore}% correlation). Amplifies hybridized parameter weights during synthesis.`;
        } else if (status === 'ACTIVE_CO_ACTIVATION') {
          impact = `Stable co-firing (${finalScore}% correlation). Standard parameter hybridization without decay penalties.`;
        } else if (status === 'NEUTRAL') {
          impact = `Moderate co-firing (${finalScore}% correlation). Standard baseline parameter weighting.`;
        } else {
          impact = `Divergent signals (${finalScore}% correlation). LTD decay enforces tightened stop loss (-1.0%) to preserve bankroll.`;
        }

        cells[i][j] = {
          rowKey: row.key,
          colKey: col.key,
          rowLabel: row.label,
          colLabel: col.label,
          correlationScore: finalScore,
          synergyPnl: Number(combinedPnl.toFixed(2)),
          winRatePct,
          status,
          isTopPair,
          hybridizationImpact: impact
        };
      }
    }

    return {
      axisNodes,
      cells
    };
  }

  public getPlasticitySummary() {
    this._recalculateTopEarnerAndBoosts();
    const topEarner = Object.values(this.data.synapticMatrix || {}).find(n => n.isTopEarner) || null;
    const heatmapData = this.getAdaptiveHeatmapData();

    const knownPatterns = [
      'CONFLUENCE_TRIPLE_CONFIRMATION',
      'CONFLUENCE_RSI_ORDERBOOK',
      'CONFLUENCE_ICHIMOKU_VOL_SURGE',
      'CONFLUENCE_ORDERBOOK_ICHIMOKU',
      'CONFLUENCE_RSI_VOL_SURGE',
      'CONFLUENCE_ICHIMOKU_RSI',
      'RAPID_SCALP_RSI',
      'ORDERBOOK_IMBALANCE'
    ];
    const strategyRankings = knownPatterns.map(p => this.evaluateAdaptiveSetupPreference({
      patternType: p,
      symbol: 'BTC-USD',
      side: 'YES',
      category: 'crypto'
    })).sort((a, b) => b.combinedScore - a.combinedScore);

    return {
      hallOfFame: this.data.hallOfFame,
      recentEvents: this.data.synthesisEvents.slice(0, 15),
      synapticMatrix: this.data.synapticMatrix,
      consecutiveLosses: this.data.consecutiveLosses || 0,
      contractWinStreaks: this.data.contractWinStreaks || {},
      topEarner,
      heatmapData,
      strategyRankings,
      lastUpdated: this.data.lastUpdated
    };
  }

  /**
   * Evaluates how strongly the Adaptive Weight Memory favors a specific combination of indicators & strategy pattern.
   * Higher LTP scores (+1.5x top earner boost) increase preference and trade sizing multiplier.
   * Depressed LTD scores reduce preference and position allocation.
   */
  public evaluateAdaptiveSetupPreference(setup: {
    patternType: string;
    symbol: string;
    side: 'YES' | 'NO';
    activeIndicators?: string[];
    spotTA?: any;
    winRules?: string[];
    category?: string;
  }): {
    patternType: string;
    combinedScore: number;
    isFavored: boolean;
    confluenceHeatmapPct: number;
    shrunkKellyMultiplier: number;
    sizeMultiplier: number;
    topEarnerInvolved: boolean;
    activeComponents: { key: string; label: string; score: number; netPnlUsd: number; category: string }[];
    reason: string;
  } {
    this._recalculateTopEarnerAndBoosts();
    const matrix = this.data.synapticMatrix || {};

    const mapping = unifiedDataHandler.resolveCorrelatedSpotPair(setup.symbol, setup.symbol, setup.category || 'crypto');
    const spotPair = mapping.isCryptoSpot ? mapping.correlatedSpotPair : 'NON_CRYPTO';

    const keysToLookUp: { key: string; label: string; category: string }[] = [
      { key: `pattern:${setup.patternType}`, label: `${setup.patternType} Strategy`, category: 'PATTERN' },
      { key: `asset:${spotPair}`, label: `${spotPair} Spot`, category: 'ASSET' },
      { key: `side:${setup.side}`, label: `${setup.side} Contract Side`, category: 'CONTRACT_SIDE' }
    ];

    if (setup.spotTA) {
      if (setup.spotTA.ichimokuState && setup.spotTA.ichimokuState !== 'NEUTRAL_IN_CLOUD') {
        keysToLookUp.push({ key: 'indicator:ICHIMOKU_CLOUD', label: 'Ichimoku Cloud Trend', category: 'INDICATOR' });
      }
      if (typeof setup.spotTA.rsi === 'number' && (setup.spotTA.rsi <= 48 || setup.spotTA.rsi >= 52)) {
        keysToLookUp.push({ key: 'indicator:RSI', label: 'RSI Momentum', category: 'INDICATOR' });
      }
      if (setup.spotTA.volumeSurgeRatio && setup.spotTA.volumeSurgeRatio >= 1.2) {
        keysToLookUp.push({ key: 'indicator:VOLUME_SURGE', label: 'Volume Surge Ratio', category: 'INDICATOR' });
      }
      if (setup.spotTA.isDoji) {
        keysToLookUp.push({ key: 'indicator:DOJI', label: 'Doji Reversal Candlestick', category: 'INDICATOR' });
      }
    }

    if (Array.isArray(setup.activeIndicators)) {
      for (const ind of setup.activeIndicators) {
        if (ind.includes('ORDERBOOK') || ind === 'ORDERBOOK_IMBALANCE') {
          keysToLookUp.push({ key: 'indicator:ORDERBOOK_IMBALANCE', label: 'Orderbook Depth Imbalance', category: 'INDICATOR' });
        }
      }
    }

    if (Array.isArray(setup.winRules)) {
      for (const r of setup.winRules) {
        keysToLookUp.push({ key: `rule:${r}`, label: `${r} Rule`, category: 'RULE' });
      }
    }

    const activeComponents: { key: string; label: string; score: number; netPnlUsd: number; category: string }[] = [];
    let sumScore = 0;
    let topEarnerInvolved = false;

    for (const item of keysToLookUp) {
      const node = matrix[item.key];
      const score = node ? node.effectiveStrengthScore : 10;
      const netPnl = node ? node.totalNetPnlUsd : 0;
      if (node && node.isTopEarner) topEarnerInvolved = true;

      activeComponents.push({
        key: item.key,
        label: item.label,
        score,
        netPnlUsd: netPnl,
        category: item.category
      });
      sumScore += score;
    }

    let avgScore = keysToLookUp.length > 0 ? sumScore / keysToLookUp.length : 12;
    const topEarnerBonus = topEarnerInvolved ? 1.20 : 1.0;
    
    // Priority Strategy Boosts: RAPID_SCALP_RSI & CONFLUENCE_ORDERBOOK_ICHIMOKU (Enhancement #1)
    const isTopTierStrategy = setup.patternType === 'RAPID_SCALP_RSI' || setup.patternType === 'CONFLUENCE_ORDERBOOK_ICHIMOKU' || setup.patternType === 'DOJI_EXHAUSTION_REVERSAL' || setup.patternType === 'GEMINI_LEAD_LAG_SIGNAL';
    const isLowTierStrategy = (setup.patternType.includes('DOJI') || setup.patternType.includes('WILDCARD')) && setup.patternType !== 'DOJI_EXHAUSTION_REVERSAL';
    const isSolAsset = setup.symbol.includes('SOL') || spotPair.includes('SOL');

    if (isTopTierStrategy) avgScore += 6.0;
    if (isSolAsset) avgScore += 4.0;
    if (isLowTierStrategy) avgScore -= 6.0;

    const combinedScore = Number((avgScore * topEarnerBonus).toFixed(1));
    const isFavored = combinedScore >= 12.0 || isTopTierStrategy;

    // Calculate confluence heatmap score between 2 active indicators / parameters
    const activeNodes = keysToLookUp
      .map(k => matrix[k.key])
      .filter((n): n is SynapticComponentNode => Boolean(n));

    let maxPairwiseConfluence = 0;
    if (activeNodes.length >= 2) {
      for (let i = 0; i < activeNodes.length; i++) {
        for (let j = i + 1; j < activeNodes.length; j++) {
          const score = this.calculatePairwiseHeatmapScore(activeNodes[i], activeNodes[j]);
          if (score > maxPairwiseConfluence) {
            maxPairwiseConfluence = score;
          }
        }
      }
    } else if (activeNodes.length === 1) {
      maxPairwiseConfluence = Math.min(98, Math.max(10, Math.round(activeNodes[0].effectiveStrengthScore * 3)));
    } else {
      maxPairwiseConfluence = 75;
    }

    const confluenceHeatmapPct = maxPairwiseConfluence;

    // Scale Kelly Multiplier using Shrinkage Estimators
    let shrunkKellyMultiplier: number;
    let sizeMultiplier: number;
    
    // Variance-Adjusted Capital Allocation: Shrinkage Estimator for Kelly Fraction
    const patternNode = activeNodes.find(n => n.category === 'PATTERN');
    let p_shrunk = 0.5; // neutral prior
    if (patternNode) {
      const wins = patternNode.winCount;
      const losses = patternNode.lossCount;
      const n = wins + losses;
      const c = 10; // Prior weight (shrinkage strength)
      p_shrunk = (wins + 0.5 * c) / (n + c);
    }
    
    // Fractional Kelly Calculation: f* = p - (1-p) = 2p - 1
    // We apply a fractional cap (e.g., 0.5) to manage drawdown volatility.
    const fullKelly = Math.max(0, 2 * p_shrunk - 1);
    const fractionalKelly = fullKelly * 0.5; 
    
    shrunkKellyMultiplier = Number(Math.max(0.1, fractionalKelly).toFixed(2));
    sizeMultiplier = shrunkKellyMultiplier;

    // Apply Top Tier Strategy 1.5x Kelly Boost & SOL Asset Tilt
    if (isTopTierStrategy) {
      shrunkKellyMultiplier = Number((shrunkKellyMultiplier * 1.50).toFixed(2));
      sizeMultiplier = Number((sizeMultiplier * 1.50).toFixed(2));
    }
    if (isSolAsset) {
      sizeMultiplier = Number((sizeMultiplier * 1.35).toFixed(2));
    }
    if (isLowTierStrategy) {
      shrunkKellyMultiplier = Number((shrunkKellyMultiplier * 0.50).toFixed(2));
      sizeMultiplier = Number((sizeMultiplier * 0.50).toFixed(2));
    }

    const favoredComponentsStr = activeComponents
      .filter(c => c.score >= 15)
      .map(c => `${c.label} (${c.score}pts)`)
      .join(', ');

    const reason = isFavored
      ? `[ADAPTIVE WEIGHT FAVORED] Setup score: ${combinedScore} pts. Variance-Adjusted Kelly Size: ${shrunkKellyMultiplier}x (Shrunk Win Prob: ${(p_shrunk*100).toFixed(1)}%). Favored components: ${favoredComponentsStr || 'High Synaptic Weight'}.`
      : `[ADAPTIVE WEIGHT DEPRESSED] Setup score: ${combinedScore} pts (Oja weight depressed). Variance-Adjusted Kelly Size: ${shrunkKellyMultiplier}x.`;

    return {
      patternType: setup.patternType,
      combinedScore,
      isFavored,
      confluenceHeatmapPct,
      shrunkKellyMultiplier,
      sizeMultiplier,
      topEarnerInvolved,
      activeComponents,
      reason
    };
  }

  /**
   * Ranks candidate trade opportunities by their Adaptive Preference Score.
   * Ensures the bot favors the strategy/indicator combinations with the strongest Adaptive Oja memory.
   */
  public rankCandidatesByAdaptivePreference<T extends { setup: any }>(candidates: T[]): (T & { adaptivePreference: ReturnType<typeof PlasticityModifierEngine.prototype.evaluateAdaptiveSetupPreference> })[] {
    const evaluated = candidates.map(c => ({
      ...c,
      adaptivePreference: this.evaluateAdaptiveSetupPreference(c.setup)
    }));

    evaluated.sort((a, b) => b.adaptivePreference.combinedScore - a.adaptivePreference.combinedScore);
    return evaluated;
  }
}

export const plasticityEngine = new PlasticityModifierEngine();
